// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApi.Infrastructure;

#nullable disable

namespace StoreApi.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StoreApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Printed books and ebooks",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Men and Women apparel",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home and kitchen",
                            IsActive = true,
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("StoreApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest smartphone model",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Powerful laptop for work and play",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1299.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-cancelling over-ear headphones",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness tracking smartwatch",
                            IsActive = true,
                            Name = "Smartwatch",
                            Price = 179.50m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable bluetooth speaker",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 59.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bestselling fiction novel",
                            IsActive = true,
                            Name = "Bestseller Novel",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delicious recipes from around the world",
                            IsActive = true,
                            Name = "Cookbook",
                            Price = 24.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive C# programming guide",
                            IsActive = true,
                            Name = "C# Programming",
                            Price = 39.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Illustrated storybook for kids",
                            IsActive = true,
                            Name = "Children's Book",
                            Price = 12.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Page-turning mystery thriller",
                            IsActive = true,
                            Name = "Mystery Thriller",
                            Price = 17.50m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cotton T-Shirt",
                            IsActive = true,
                            Name = "T-Shirt",
                            Price = 14.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Denim jeans",
                            IsActive = true,
                            Name = "Jeans",
                            Price = 39.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight jacket",
                            IsActive = true,
                            Name = "Jacket",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable everyday sneakers",
                            IsActive = true,
                            Name = "Sneakers",
                            Price = 69.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm cotton hoodie",
                            IsActive = true,
                            Name = "Hoodie",
                            Price = 49.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kitchen blender for smoothies",
                            IsActive = true,
                            Name = "Blender",
                            Price = 49.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2-slice toaster",
                            IsActive = true,
                            Name = "Toaster",
                            Price = 29.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact vacuum cleaner",
                            IsActive = true,
                            Name = "Vacuum Cleaner",
                            Price = 129.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automatic drip coffee maker",
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic memory foam pillow",
                            IsActive = true,
                            Name = "Pillow",
                            Price = 34.99m,
                            StockQuantity = 140
                        });
                });

            modelBuilder.Entity("StoreApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("StoreApi.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StoreApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
